export const PERMISSIONS = {
  PROJECT_CREATE: 'project.create',
  PROJECT_READ: 'project.read',
  PROJECT_MANAGE: 'project.manage',
  TASK_CREATE: 'task.create',
  TASK_READ: 'task.read',
  TASK_UPDATE: 'task.update',
  ADMIN: 'admin',
  WORKSPACE_MEMBERS_READ: 'workspace.members.read',
  WORKSPACE_MEMBERS_INVITE: 'workspace.members.invite',
  WORKSPACE_MEMBERS_UPDATE: 'workspace.members.update',
  WORKSPACE_MEMBERS: 'workspace.members',
  WORKSPACE_ROLES_READ: 'workspace.roles.read',
  WORKSPACE_ROLES_UPDATE: 'workspace.roles.update',
  WORKSPACE_SECURITY_READ: 'workspace.security.read',
  WORKSPACE_VOICE_MANAGE: 'workspace.voice.manage',
  VOICE_NOTES_READ: 'voice_notes.read',
  VOICE_NOTES_UPDATE: 'voice_notes.update',
  ATTENDANCE_READ: 'attendance.read',
  ATTENDANCE_MANAGE: 'attendance.manage',
  ATTENDANCE_USE: 'attendance.use',
  LEAVE_USE: 'leave.use',
  LEAVE_APPROVE: 'leave.approve',
  GROUPS_CREATE: 'groups.create',
  CLIENT_READ: 'client.read',
  CLIENT_MANAGE: 'client.manage',
} as const;

export type Permission = typeof PERMISSIONS[keyof typeof PERMISSIONS];

